# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

    
env:
  ## Sets environment variable
  MICROSERVICES: "commonlib"
  REGION: "ap-southeast-1"
  
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout servicehub-platform-commonlib Repo
        uses: actions/checkout@v2

      - name: Maven Build  
        run: /opt/apache-maven-3.8.4/bin/mvn clean install
        
      - name: SonarQube Scan
        continue-on-error: true
        uses: unobankasia/sonarqube-action@v1.1.6
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: myproject
          binaries: target/classes
